/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 untitled.glb
*/

import { useGLTF } from '@react-three/drei'
// src\assets\untitled.glb
// const path = '../models/untitled.glb'
// public\models\low_poly_american_pickup_truck.glb
const path = 'models/untitled.glb'
export function House(props) {
  const { nodes, materials } = useGLTF(path)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[0, 0, Math.PI]}>
          <mesh geometry={nodes.Glass.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Window.geometry} material={materials.Windows} />
        </group>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Main_Mat} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.Roof} />
      </group>
    </group>
  )
}

useGLTF.preload(path)
